Repository Arjun-MST/collaborative-work, pull requests merged in 2025-06, with the labels that each got.

#2 Prakriti
  index.html
Labels: enhancement

#3 first change
  index.html
  style.css
Labels: good first issue

#12 Arjun
  index.html
Labels: documentation
